[[build.env]]
name = "BP_NODE_VERSION"
value = "14"  # Ou a versão que você está usando

[[build.env]]
name = "BP_NPM_BUILD_ARGUMENTS"
value = "--unsafe-perm"  # Pode ser necessário para instalar dependências globais

[[build.buildpacks]]
id = "paketo-buildpacks/node-engine"
version = "0.2.1"

[[build.buildpacks]]
id = "paketo-buildpacks/npm"
version = "0.2.0"

[[build.buildpacks]]
id = "paketo-buildpacks/yarn"
version = "0.2.1"

[[build.buildpacks]]
id = "paketo-buildpacks/node-run"
version = "0.3.0"

# Adicionar configuração para o Chromium (se necessário)
[[build.buildpacks]]
id = "paketo-buildpacks/node-engine"
version = "0.2.1"

[[build.buildpacks]]
id = "paketo-buildpacks/node"
version = "0.2.1"
